-- Schema definitions for SQLite / PostgreSQL

-- 1. Conversations History Table
-- PostgreSQL:
-- CREATE TABLE conversations (
--   id SERIAL PRIMARY KEY,
--   chat_id TEXT NOT NULL,
--   role TEXT NOT NULL,
--   content TEXT NOT NULL,
--   subagent TEXT,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- SQLite:
-- CREATE TABLE conversations (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   chat_id TEXT NOT NULL,
--   role TEXT NOT NULL,
--   content TEXT NOT NULL,
--   subagent TEXT,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

-- 2. Reminders Table
-- PostgreSQL:
-- CREATE TABLE reminders (
--   id SERIAL PRIMARY KEY,
--   chat_id TEXT NOT NULL,
--   message TEXT NOT NULL,
--   due_at TIMESTAMP NOT NULL,
--   sent BOOLEAN DEFAULT FALSE,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- SQLite:
-- CREATE TABLE reminders (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   chat_id TEXT NOT NULL,
--   message TEXT NOT NULL,
--   due_at DATETIME NOT NULL,
--   sent BOOLEAN DEFAULT FALSE,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

-- 3. Telemetry/Error Logs Table
-- PostgreSQL:
-- CREATE TABLE logs (
--   id SERIAL PRIMARY KEY,
--   category TEXT NOT NULL,
--   message TEXT NOT NULL,
--   details TEXT,
--   duration_ms INTEGER,
--   is_error BOOLEAN DEFAULT FALSE,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- SQLite:
-- CREATE TABLE logs (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   category TEXT NOT NULL,
--   message TEXT NOT NULL,
--   details TEXT,
--   duration_ms INTEGER,
--   is_error BOOLEAN DEFAULT FALSE,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

-- 4. Background Tasks Registry
-- PostgreSQL / SQLite:
-- CREATE TABLE tasks (
--   task_id TEXT PRIMARY KEY,
--   chat_id TEXT NOT NULL,
--   status TEXT NOT NULL,
--   description TEXT NOT NULL,
--   created_at TIMESTAMP NOT NULL,
--   completed_at TIMESTAMP
-- );

-- 5. Expenses Table
-- PostgreSQL:
-- CREATE TABLE expenses (
--   id SERIAL PRIMARY KEY,
--   chat_id TEXT NOT NULL,
--   amount DOUBLE PRECISION NOT NULL,
--   category TEXT NOT NULL,
--   description TEXT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- SQLite:
-- CREATE TABLE expenses (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   chat_id TEXT NOT NULL,
--   amount REAL NOT NULL,
--   category TEXT NOT NULL,
--   description TEXT NOT NULL,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

-- 6. Research Notes Table
-- PostgreSQL:
-- CREATE TABLE research_notes (
--   id SERIAL PRIMARY KEY,
--   chat_id TEXT NOT NULL,
--   title TEXT NOT NULL,
--   content TEXT NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- SQLite:
-- CREATE TABLE research_notes (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   chat_id TEXT NOT NULL,
--   title TEXT NOT NULL,
--   content TEXT NOT NULL,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- );

-- 7. Dynamic Runtime Tooling Layer
-- CREATE TABLE IF NOT EXISTS runtime_skills (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(100) UNIQUE NOT NULL,
--     description TEXT NOT NULL,
--     param_schema JSONB NOT NULL,
--     code TEXT NOT NULL,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- 8. Thread-to-Worker Routing Matrix
-- CREATE TABLE IF NOT EXISTS thread_assignments (
--     thread_id BIGINT PRIMARY KEY,
--     worker_name VARCHAR(100) NOT NULL,
--     pinned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- 9. Long-Term Semantic User Attributes
-- CREATE TABLE IF NOT EXISTS user_profile (
--     id SERIAL PRIMARY KEY,
--     key VARCHAR(255) UNIQUE NOT NULL,
--     value JSONB NOT NULL,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- 10. Episodic Action Ledger & Audit Logs
-- CREATE TABLE IF NOT EXISTS episodic_memory (
--     id SERIAL PRIMARY KEY,
--     session_id VARCHAR(255), 
--     interaction_type VARCHAR(50),
--     content TEXT NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
